require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.ayu"
require "user.colorscheme"
require "user.todo_comments"
require "user.highlight_colors"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim_tree"
require "user.evil_lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.orgmode"
require "user.ufo"
require "user.leap"

require("nvim-tree").setup()
